ENTRY(_start)
PHDRS { text PT_LOAD; data PT_LOAD; }


SECTIONS {
  /* _pmem_start and _entry_offset are defined in LDFLAGS */
  . = _pmem_start + _entry_offset;
  .text : {
    *(entry)
    *(.text*)
  } : text
  etext = .;
  _etext = .;
  .rodata : {
    *(.rodata*)
  }
  .data : {
    *(.data)
  } : data
  edata = .;
  _data = .;
  .bss : {
	_bss_start = .;
    *(.bss*)
    *(.sbss*)
    *(.scommon)
  }
  . = 0x0f000000;
  _heap_start = ALIGN(0x400);
  . = _heap_start + 0x1c00;
  _heap_end = .;
  _stack_top = ALIGN(0x400);
  . = _stack_top + 0x400;
  _stack_pointer = .;
  end = .;
  _end = .;  
}
