= Shell学习记录
Doc Writer yunhaigushu;
v1.0, 2025-04-11
:toc:
:toc-title: Directory
== Shell语法
=== 多条指令使用
* 无条件顺序执行:cmd1; cmd2
* 上条命令成功时执行下条命令:cmd1 && cmd2
* 上条命令失败时执行下条命令:cmd1 || cmd2
* 后台执行该命令:cmd &
* 上一条命令的输出作为下一条命令的输入:cmd1 | cmd2

=== 文件描述符和重定向
[cols="2*^",options="header"]
|===
| 文件描述符 | 含义
| 0 | 标准输入
| 1 | 标准输出
| 2 | 标准错误输出
|===
[cols="2*^",options="header"]
|===
| 命令 | 说明
| `command > file` | 将输出重定向到 `file`。
| `command < file` | 将输入重定向到 `file`。
| `command >> file` | 将输出以追加的方式重定向到 `file`。
| `n > file` | 将文件描述符为 `n` 的文件重定向到 `file`。
| `n >> file` | 将文件描述符为 `n` 的文件以追加的方式重定向到 `file`。
| `n >& m` | 将输出文件 `m` 和 `n` 合并。
| `n <& m` | 将输入文件 `m` 和 `n` 合并。
| `<< tag` | 将开始标记 `tag` 和结束标记 `tag` 之间的内容作为输入。
| `command1 \| command2` | 将命令1的输出作为命令2的输入
|===

=== 通配
* `?` 和 `*` 用于匹配一个和任意个字符 
* `{}` 当你有一系列的指令，其中包含一段公共子串时，可以用花括号来自动展开这些命令 +

[source,bash]
----
convert image.{png,jpg}
# 会展开为
convert image.png image.jpg

cp /path/to/project/{foo,bar,baz}.sh /newpath
# 会展开为
cp /path/to/project/foo.sh /path/to/project/bar.sh /path/to/project/baz.sh /newpath

# 也可以结合通配使用
mv *{.py,.sh} folder
# 会移动所有 *.py 和 *.sh 文件

mkdir foo bar

# 下面命令会创建 foo/a, foo/b, ... foo/h, bar/a, bar/b, ... bar/h 这些文件
touch {foo,bar}/{a..h}
----

=== 文件操作相关
[source,bash]
----
xrags [options] [command] 
----
该命令用于将标准输入转换为命令command的参数,常配合|使用 

[source,bash]
----
tee [OPTIONS] [FILE] 
----
该命令用于将标准输入的数据写到多个文件或者标准输出,常配合|使用 +
OPTIONS=-a时表示追加

[source,bash]
----
find 指定目录 -name '*.ext'
----
该命令用于查找文件,也可以对查找到的命令进行批量处理,平替命令为 `fd`,用 `tldr find` 查看更多示例

[source,bash]
----
grep "模式字符串" 路径/到/文件
----
该命令用于查找文件中匹配字符串的内容,常用选项如下: +
`-C N` 打印匹配字符串的上下各N行的内容 +
`-R` 表示递归查找目录下所有文本 +
`-v` 表示输出不匹配的内容,表示反选 +

[source,bash]
----
ln [-s|--symbolic] /路径/到/文件或目录 路径/到/符号链接
----
该命令用于创建符号链接,还挺好用的

=== 程序安装命令
* 安装tar.bz2包

[source,bash]
----
tar -jxvf example-1.2.3-1.tar.bz2
----
`-j` 使用bzip2解压.bz2格式压缩包 +
`-x` 表示解压,解压.tar格式压缩包 +
`-v` 在终端显示详细信息 +
`-f` 指定文件名,这里指example-1.2.3-1.tar.bz2 +
解压后的文件可能为安装好的程序,创建桌面快捷方式后即可使用;也可能为源码,需要进行构建安装才能使用

* 安装deb包

[source,bash]
----
sudo dpkg -i example-1.2.3-1.deb
----
deb包只能在su环境下进行安装,除了使用 `-i` 进行安装外,还可以使用 `-l` 进行查询,使用 `-e` 进行卸载

* 安装tar.gz包

[source,bash]
----
tar -xzvf example-1.2.3-1.tar.gz
----
`-z` 使用gzip解压.gz格式压缩包其他选项含义同tar.bz2 +
解压得到的内容也同tar.bz2



