= C阶段总结
Doc Writer yunhaigushu;
v1.0, 2025-07-20
:toc: left
:toc-title: Directory

C阶段主要内容有三点: NEMU的基础设施和指令集的实现, NPC的基础设施和硬件的视线, AM的完善

== NEMU
=== 概述
* 支持RV32IM_Zicsr指令集, 其中FENCE, FENCE.TSO, PAUSE指令暂不支持, ECALL指令用于进入中断, EBREAK指令用于结束程序. +
* 支持MEPC, MCAUSE, MTVEC, MSTATUS四个CSRS, MRET用于从中断返回. +
* 支持ITRACE, MTRACE, FTRACE, ETRACE, DTRACE, Difftest的功能. +
* 支持设备串口, 定时器, 键盘, VGA, 声卡, 另外两个设备disk, sdcard还没有配置使用. +
* 支持SDB, 该调试模式可以运行指定数量指令, 设置监控点, 查看寄存器的值, 查看内存的值. + 

=== 工具
* 使用capstone项目的反汇编功能处理指令, 主要用于ITRACE. +
* 使用fixdep和kconfig项目生成Kconfig配置系统, 通过make menuconfig调用. +
* 使用gen-expr项目测试sdb中有关表达式的实现. +
* 使用spike-diff项目为nemu的Difftest的功能提供ref. +

== NPC
=== 硬件
* NPC是单周期CPU, 使用DPI-C功能完成取值和访存操作, 在时钟上升沿更新PC, GPRS, CSRS的值. +
* NPC支持RV32E_Zicsr指令集, 其中FENCE, FENCE.TSO, PAUSE指令暂不支持, ECALL指令用于进入中断, EBREAK指令用于结束程序. +
* 支持MEPC, MCAUSE, MTVEC, MSTATUS四个CSRS, MRET用于从中断返回. +

=== NPC仿真主循环
仿真主程序::
每当clk变化时, 重新计算电路状态, 仅当上升沿时记录波形, 仅当NPC的PC值发生变化时算完成一条指令. +
[source, C]
----
0x80000000: inst1 +
0x80000004: inst2 +
0x80000008: ebreak +
----
仿真主程序::
例如上面有三条指令, 在sdb中运行一条指令后, 寄存器状态为执行位 `inst1` 后的状态, PC值为 `0x80000004`. 但其实这时 `inst2` 已经执行完毕, 无论是访存还是计算都完成了, 只是还没有将状态更新到寄存器中. 同理, 再次运行一条指令后, PC值为 `0x80000008`, 但其实这时 `ebreak` 指令已经结束了程序, 再次执行会提示 `程序已经结束`.

[source, C]
----
while (npcstate.state == NPC_RUNNING)
{
ysyx_25050136_NPC->clk ^= 1;
// 复位
reset();
// 计算电路状态
ysyx_25050136_NPC->eval();
// 记录上升沿
IFDEF(CONFIG_FST, tfp->dump(sim_time));
// 推动仿真进行
sim_time++;
// 指令计算
if (sim_time >= (reset_time + stop_time) && ysyx_25050136_NPC->pc_o != pc__)
{
    pc_pre = pc__;
    inst_pre = *(uint32_t *)(pmem + pc_pre - CONFIG_MBASE);
    pc__ = ysyx_25050136_NPC->pc_o;
    break;
}
}
----

=== 软件
* 支持设备串口, 定时器. 这些在DPI-C的访存函数中实现. +
* 支持Kconfig配置. +
* 支持ITRACE, MTRACE, FTRACE, Difftest的功能, 其中Difftest的ref是nemu. +
* 支持SDB, 该调试模式可以运行指定数量指令, 设置监控点, 查看寄存器的值, 查看内存的值. +

== AM
=== Klib
主要添加了stdio库, string库的主要库函数, 简易实现了stdlib中malloc的功能, 但是没有实现free +
 
=== IOE
* `audio`: AM声卡控制器信息(AM_AUDIO_CONFIG), AM声卡控制寄存器(AM_AUDIO_CTRL), AM声卡状态寄存器(AM_AUDIO_STATUS), AM声卡播放寄存器(AM_AUDIO_PLAY) +
* `VGA`: AM显示控制器信息(AM_GPU_CONFIG), AM帧缓冲控制器(AM_GPU_FBDRAW) +
* `键盘`: AM键盘控制器(AM_INPUT_KEYBRD) +
* `时钟`: AM实时时钟(AM_TIMER_RTC), AM系统启动时间(AM_TIMER_UPTIME) +

=== CTE
* `cte_init`: cte初始化, 配置中断服务程序的回调函数. +
* `__am_irq_handle`: 中断服务程序, 识别不同中断. +
* `kcontext`: 创建一个线程. +
* `yield`: 自陷函数. +

== 历史遗留问题
[green]##1> 有关difftest, 目前NPC涉及到设备访存时, 采用了跳过该指令和其前面或者后面一条指令来解决的, 按理来说这是不正确的, 但是还是这样做了##