= Git知识点总结
Doc Writer yunhaigushu;
v1.0, 2025-05-1
:toc:
:toc-title: Directory

== git教程
link:https://git-scm.com/book/zh/v2/%e8%b5%b7%e6%ad%a5-%e5%85%b3%e4%ba%8e%e7%89%88%e6%9c%ac%e6%8e%a7%e5%88%b6[点我查看中文的git教程]

== git的配置
[source,bash]
git config

用于配置git,有三个等级,由高到低分别是系统级,全局和本地(`--system`,`--global`,`--local`),在实际使用中,低一级的配置将会覆盖高一级的配置,一般对于个人用户选择 `--global` 即可 

=== 常用配置
[source,bash]
git config --global user.name "yunhai"
git config --global user.email "xxxx@.com"

上面用于设置用户的名字和邮箱,是git使用必须的
[source,bash]
git config --global core.editor gedit
git config --global core.pager ''

上面用于配置git使用的编辑器和分页器,两者默认是vi和less,上面将其配置为gedit和不分页

[source,bash]
git config --global http.proxy 'http://127.0.0.1:7890'
git config --global https.proxy 'https://127.0.0.1:7890'

上面用于给git设置代理,这个应该是https的代理,前面应该一样,最后7890是clash的端口号,改成自己的就好了

[source,bash]
git config --global credential.helper store

当使用https链接git远程仓库时,每次都要输入用户名和密码,只需要配置上面这个,将能将你用户名和密码保存到本地,下次push时它会自动去匹配,不用你输入了,默认保存为~/.git-credentials

[source,bash]
git cofing --global init.defaultbranch master

上面用于设置每次git init后默认分支的名字

=== 配置其他命令
[source,bash]
git config -l --global
git config --global --edit
git config --global --unset core.pager

第一条命令用于列出你的全局git配置 +
第二条命令用于通过编辑器打开全局git配置文件,图形化便于改 +
第三条命令用于取消某个全局git配置选项 +

== git命令
=== git常识
Git 是一个分布式版本控制系统,支持多个分支和多个远程仓库。

1. **分支**:
   - Git 可以有多个分支,每个分支是代码库的一个快照。
   - 本地分支和远程分支可以关联,用于同步代码。
   - 分支的切换使用 `git checkout` 或 `git switch`。

2. **文件状态**:
   - **未跟踪(Untracked)**:文件未被 Git 跟踪。
   - **已跟踪(Tracked)**:
     - **未修改(Unmodified)**:文件未被修改。
     - **已修改(Modified)**:文件被修改,但未添加到暂存区。
     - **已暂存(Staged)**:文件的修改已添加到暂存区,等待提交。

3. **三个区域**:
   - **工作区(Working Directory)**:当前正在编辑的文件。
   - **暂存区(Staging Area)**:使用 `git add` 将修改添加到暂存区。
   - **本地仓库(Local Repository)**:使用 `git commit` 将暂存区的内容提交到本地仓库。
   - **远程仓库(Remote Repository)**:使用 `git push` 将提交推送到远程仓库。

=== git常用命令
[source,bash]
git init

用于初始化git,在文件夹中使用,会得到.git目录

[source,bash]
git add -A
git commit -m "第一次"

第一条命令用于将所有的文件添加到暂存区;第二条命令用于将暂存区的所有内容提交到本地仓库,并通过 `-m` 附赠提交说明信息

[source,bash]
git remote -v
git remote add 远程仓库名字 远程仓库的URL
git remote remove 远程仓库名字
git remote rename 旧名字 新名字
git remote set-url 远程仓库名字 新URL
git remote get-url 远程仓库名字

含义不解释了,一般添加远程仓库用第二条就好了

[source,bash]
git push 远程仓库名 本地分支名
git push --all 远程仓库名
git push 远程仓库名 [-d|--delete] 远程分支名

第一条表示将指定本地分支的更改推送到其远程对应分支,可以添加 `-u` 将该远程分支设为该本地分支 push/pull 的默认目标分支, 也可以添加 `-force` 表示强制提交,一般就是使用第一条

[source,bash]
git pull 远程仓库名 分支名

表示从远程仓库拉取对应分支

[source,bash]
git log 本地分支名
git status

第一条是查看本地分支的commit记录;第二条用于查看git仓库中文件的变更状态,可以添加 `-s` 以简短形式展示

[source,bash]
git branch -a
git branch 分支名
git branch [-d|--delete] 分支名

第一条用于列出所有分支;第二条用于创建新的分支;第三条用于删除本地分支

[source,bash]
git checkout -b 分支名
git checkout 分支名

第一条表示创建并切换到新的分支;第二条表示切换到对应分支