= Make学习记录
Doc Writer yunhaigushu;
v1.0, 2025-04-11
:toc: left
:toc-title: Directory
:toclevels: 4
== Makefile常识
=== 规则
`Makeflie` 文件简单来说就是用来生成文件的。 +
如图1所示，我们需要使用 `a.txt`,`b.txt`,`c.txt` 三个文件来生成 `x.txt` 文件。

.生成文件
image::../images/a.png[]

`Makefile` 文件由规则组成，每个规则由三部分组成：目标、依赖和命令。 +
[source,make]
----
# 目标文件: 依赖文件1 依赖文件2
#   命令
m.txt: a.txt b.txt
	cat a.txt b.txt > m.txt
----
`make` 命令默认执行第一个规则。执行时，`make` 会检查目标文件是否存在，如果不存在 或者依赖文件有更新，则执行命令。如果依赖文件未就绪，`make` 会先执行依赖文件的规则，直到所有依赖文件都就绪为止。 +
`make` 命令会自动判断目标文件是否需要更新，如果需要更新，则执行命令。 +
所以实现上面目标的 `Makefile` 文件如下：
[source,make]
----
x.txt: m.txt c.txt
	cat m.txt c.txt > x.txt

m.txt: a.txt b.txt
	cat a.txt b.txt > m.txt
----
此时执行`make`命令将得到x.txt文件

=== 特殊目标
==== 伪目标
我们在执行 `make clean` 时并没有生成 `clean` 文件，所以每次都将执行一边命令。
[source,make]
----
clean:
    rm -f x.txt m.txt
----
当然我们也可以将 `clean` 标记为一个伪目标，这样即使存在 `clean文件` ，命令也会执行
[source,make]
----
.PHONY: clean
clean:
    rm -f x.txt m.txt
----

==== 用于保存中间文件
make在运行时像 `.i` 文件这样的中间文件是会被自动删除的,如果想要保留下来,需要一点点手段 +
`.SECONDARY` 这个特殊目标的依赖文件会被视作中间文件,且不会被删除,但是这个特殊目标的依赖文件不支持模式和通配 +
`.PRECIOUS` 这个特殊目标的效果同 `.SECONDARY` 一样,但是它的依赖文件支持模式,如 `ex%.i`

=== 多条指令
下面这么执行多条指令并不正确，因为每条指令会在不同的 shell 中执行
[source,make]
----
cd:
	pwd
	cd ..
	pwd
----
常用的解决办法是使用 `;` 将多条指令连接起来，同时配合 `\` 符号进行换行
[source,make]
----
cd:
    pwd; \
    cd ..; \
    pwd
----
或者使用 `&&` 连接符，只有前面的命令成功执行后，才会执行后面的命令
[source,make]
----
cd:
    pwd && \
    cd .. && \
    pwd
----

=== 变量与变量赋值
对于重复出现的语句都可以用**大写**的变量表示,而通常使用 `=`,`:=`,`?=`,`+=` 进行赋值,使用 `$(变量名)` 进行调用

`=` 变量的值是整个Makefile最后被指定的值 +
`:=` 变量的值就是当前位置的值,这个才是真正意义的= +
`?=` 如果变量此时没有赋值,才会赋值予等号后的值 +
`+=` 增量赋值,将值添加到原来的值之后 +
[source,make]
----
TARGET := world.out
clean:
	rm -f *.o $(TARGET)
----

=== 自动变量和内置变量
`$@` 表示目标文件,也可以表示为 `$(@)` +
`$<` 表示第一个依赖文件 +
`$^` 表示所有依赖文件 +
`$(@D)` 表示目标文件的目录相对路径 +
内置变量是一些设定好的变量,手册搜索 `Variables Used by Implicit Rules` 常用的有 +
`CC` 表示C程序编译器 +
`CXX` 表示 C\++ 程序编译器 +
`CFLAGS` 表示C程序编译器的编译选项 +
`CXXFLAGS` 表示C++程序编译器的编译选项 +
`CFLAGS` 表示C程序编译器的编译选项 +

=== 控制打印
`make` 命令前添加 `@` 符号可以禁止打印命令
[source,make]
----
@echo "hello world"
----

=== 控制错误
`make` 命令前添加 `-` 符号可以禁止打印错误
[source,make]
----
-echo "hello world"
----

=== 条件判断
涉及四个关键字 `ifeq`,`ifneq`,`ifdf`,`ifndf`.用法如下:
[source,make]
----
mode = debug
hello: hello.c
ifeq ($(mode),debug)
    @echo "debug mode" 
    gcc -g -o hello hello.c
else
    @echo "release mode"
    gcc -o hello hello.c
endif
----
`ifeq` 表示比较两个参数是否相等,参数可以是变量的值,字符串甚至空字符串;同样可以使用 `ifneq` 直接替换,表示比较两个参数是否不相等.
[source,make]
----
mode = 
hello: hello.c
ifdef mode
    @echo "debug mode" 
    gcc -g -o hello hello.c
else
    @echo "release mode"
    gcc -o hello hello.c
endif
----
`ifdef` 表示判断某个变量是否存在,或者是否被赋值;同样可以使用 `ifndef` 替代,表示判断是否不存在

== Makefile高级用法
=== Makefile模式规则
手册搜索 `Defining and Redefining Pattern Rules` +
模式规则(Pattern Rules)与普通规则不同之处在于,其目标包含一个 `%` +
`%` 可以匹配所有非空字符串,但是与通配符 `*` 不同,包含 `%` 的目标只会匹配一个目标文件 +
模式规则的依赖文件同样可以使用 `%` 来匹配,依赖文件的 `%` 的取值由目标的 `%` 决定,例如“%.o: %.c”,目标为main.o时,依赖为main.c +

使用示例：
[source,make]
----
main: main.o test.o
    $(CC) -o $@ $^ $(LDFLAGS)

%.o: %.c
    $(CC) -c $^ -o $@ $(CFLAGS)
----
此时执行make命令,会先去生成依赖文件main.o和test.o,而两者都匹配下面定义的模式规则,所以执行时会执行两条规则来生成这两个依赖文件:
[source,make]
----
main.o: main.c
    $(CC) -c $^ -o $@ $(CFLAGS)
test.o: test.c
    $(CC) -c $^ -o $@ $(CFLAGS)
----

=== Makefile的函数
make的函数分为两种,一种是内嵌函数,一种是自定义函数,前者直接引用,后者通过make的call函数间接调用. +
make内嵌函数使用格式如下: +
`$(函数名 参数1,参数2...)` +
函数的参数也可以是函数或者变量,正常嵌套使用即可

==== Flavor函数
`$(flavor variable)`
[source,make]
----
ARCC = $(ARC) shift
ARC = fuck
ARS := hoo
$(flavor ARS)
# 结果为 simple
$(flavor ARCC)
# 结果为 recursive
$(flavor ARSS)
# 结果为 undefined
----
文档中介绍变量不同的赋值方式称为变量的flavor,共有四种,常用的是两种 `simple` 和 `recursive`.
简单理解,`simple` 表示使用 `:=` 赋值的,`recursive` 表示使用 `=` 赋值的. +
这个函数用于查看变量的flavor,总共就有上面三种返回情况,其中 `undefined` 表示未定义.

==== 控制make的函数
用于提醒用户或在条件满足时停止make运行 +
包括 `error`,`warning`,`info`

===== error
`$(error text…)`
就是会报错退出运行,并且打印错误信息text到标准输出

===== info
`$(info text…)`
就是打印文本text到标准输出

==== Shell函数
`$(shell shell函数...)`
[source,make]
----
# 有a.c和b.c
CSRCS = $(shell ls)
# 会得到 CSRCS = a.c b.c
# 换行符被替换成了空格
----

==== 文本处理函数
包括 `subst`,`patsubst`,`strip`,`findstring`,`filter`,`filer-out`,`sort`,`word`,`wordlist`,`words`,`fistword`

===== subst
`$(subst from,to,text)`
[source,make]
----
$(subst ee,EE,feet on the street)
#结果为fEEt on the strEEt
----
用于实现字符串的转换,将text字符串中的from替换成to

===== findstring
`$(findstring FIND, IN)`
[source,make]
----
.PHONY: all
STR =     hello a    b   c   
FIND = $(findstring hello, $(STR))
all:
    @echo "STR = $(STR)"
    @echo "FIND = $(FIND)"
----
用于在IN字符串中寻找FIND字符串,如果找到则返回FIND字符串,没找到则返回空

===== patsubst
`$(patsubst 原模式,目标模式,文件列表)`
[source,make]
----
# 这里将$(SRC)中的文件做了转换
# 假设DIR = .   OBJDIR = obj    SRC = ./main.c ./test.c
# 那么OBJ = obj/main.o obj/test.o
OBJ := $(patsubst $(DIR)/%.c, $(OBJDIR)/%.o, $(SRC))
----
该函数常用于将检索包含到的文件做一个文件名的批量修改

===== filter
`$(filter pattern…,text)`
[source,make]
----
sources := foo.c bar.c baz.s ugh.h
$(filter %.c %.s,$(sources))
# 得到foo.c bar.c baz.s
----
过滤掉text字符串中所有不符合pattern规则的字符串,这里pattern使用%作为通配符

===== filter-out
`$(filter-out pattern…,text)`
[source,make]
----
objects=main1.o foo.o main2.o bar.o
mains=main1.o main2.o
$(filter-out $(mains),$(objects))
# 得到foo.o bar.o
----
过滤掉text字符串中所有符合pattern规则的字符串,这里pattern使用%作为通配符

===== sort
`$(sort list)`
[source,make]
----
$(sort foo bar lose lose)
# 结果为bar foo lose
----
将list中的单词按照首字母顺序排列,首字母相同则依次比较下一个字母,并且删除重复的单词

===== word
`$(word n,text)`
[source,make]
----
$(word 2, foo bar baz)
# 结果为bar
----
返回text中的第N个单词,N=0报错,N大于text中单词总数返回空

==== 文件名处理函数
包括 `dir`,`notdir`,`suffix`,`basename`,`addsuffix`,`addprefix`,`join`,`wildcard`,`realpath`,`abspath`

===== dir
`$(dir names…)`
[source,make]
----
$(dir src/foo.c hacks)
# 得到src/ ./
----
从完整路径名中取得目录

===== notdir
`$(notdir names…)`
[source,make]
----
$(notdir src/foo.c hacks)
# 得到foo.c hacks
----
从完整路径名中取得文件名

===== basename
`$(basename names…)`
[source,make]
----
$(basename src/foo.c src-1.0/bar hacks)
# 得到src/foo src-1.0/bar hacks
----
获得文件前缀名,有一个点去点;有多个点去最后一个点;没有点返回全部

===== addsuffix
`$(addsuffix suffix,names…)`
[source,make]
----
$(addsuffix .c,foo bar)
# foo.c bar.c
----
简单理解就是给names中每个单词加前缀suffix,names中的每个单词之间使用空格间隔

===== addprefix
`$(addprefix prefix,names…)`
[source,make]
----
$(addprefix src/,foo bar)
# 得到src/foo src/bar
----
简单理解就是给names中每个单词加前缀prefix,names中的每个单词之间使用空格间隔

===== join
`$(join list1,list2)`
[source,make]
----
$(join aa bb,.c .o)
# 得到aa.c bb.o
----
按照索引依次拼接list1和list2中的单词,一般要求两个参数中单词数量一致,若不一致将会原样复制多的部分单词给结果

===== wildcard
`$(wildcard 指定文件类型)` +
[source,make]
----
# 将$(DIR)目录下所有C文件找到,并给SRC
# 效果等价于$(shell find $(DIR) -name *.c)
SRC := $(wildcard $(DIR)/*.c)
----
该函数常用于包含所有需要的文件,比如一个C工程中所有的C文件

