= 一生一芯实验日志
Doc Writer yunhaigushu;
v1.0, 2025-04-11
:toc: left
:toclevels: 1
:toc-title: Directory

[[d2025-3-27]]
== 2025/3/27 实验日志
=== 今日完成工作
* 开始学习使用adoc, 利用vscodo插件完成了英文pdf, html, Docbook的转换。
* 完成一生一芯/预学习阶段/复习C语言/笨办法学C/ex0-ex10

=== 今日要点
* Valgrind的安装使用

教程给的下载地址失效, 自己进入 https://valgrind.org/downloads/current.html[Valgrind官网] 下载最新版的bz2压缩包进行源码构建安装

[[d2025-3-29]]
== 2025/3/29 实验日志
=== 今日完成工作
* 完成一生一芯/预学习阶段/复习C语言/笨办法学C/ex11-ex16
* 源码构建安装了verilatork

=== 今日要点
* C语言知识点

stdio.h库主要用于标准输入输出函数, 比如printf, scanf
stdlib.h库主要用于内存管理、进程控制函数, 比如malloc, free
string.h库主要用于字符串处理, 比如strdup(字符串复制)

分配内存不释放会造成内存泄漏, 堆积会造成内存溢出

[[d2025-3-30]]
== 2025/3/30 实验日志
=== 今日完成工作
* 完成一生一芯/预学习阶段/复习C语言/笨办法学C/ex17-ex18
* 开始进行PA0环境的搭建, 初步学习使用了gdb和tmux

=== 今日要点
* gdb

主要工作就是配置了一下环境, 让linux在错误时能够生成core文件进行gdb调试

* tmux

了解了一下session, window, pane之间的关系, 感觉吧要是熟练了可以在linux中不要鼠标操作了

[[d2025-4-1]]
== 2025/4/1 实验日志
=== 今日完成工作
* 完成了PA0的内容, 只有vim的学习跳过了, 必做题800字读后感还没写
* 完成一生一芯/预学习阶段/搭建verilator仿真环境/双控开关的设计与仿真
* 使用Makefile文件完成仿真, 实现了fst波形的输出
* 接入了NVBoard, 完成了示例程序的编译和运行
* 改写了Makefile文件, 完成了对NVBoard对双控开关的部署

=== 今日要点
* NVBoard

在编写双控开关在NVBoard上的main.cpp代码时, 没有报错但是开发板没有反应, 查阅资料发现是需要在while中调用eval(),
因为每次改变拨码开关都算是rtl电路的输入改变, 需要调用eval()来更新电路的状态

* Makefile

我现在有两个运行选项, make sim用于仿真, make run用于在NVBoard上运行, 都复制了commit提交代码

[[d2025-4-7]]
== 2025/4/7 实验日志
=== 今日完成工作
* 这段时间我安装了ubuntu24.04真机双系统
* 移植原来Vmware虚拟机上的工作内容到真机上
* 完成了复习C语言/笨办法学C/ex01-ex15的内容和课后题

=== 今日要点
* C语言知识点

字符串变量直接赋值只是将对应指针进行了赋值, 并没有复制字符串的内容。
例如str1 = str2;
当str2的内容改变时, str1也会跟着改变, (注意这里想要改变str2的内容, 需要使用strcpy函数)。

需要留意的是, str2的大小是固定的, 但使用strcpy函数改变str2内容时并不会检查是否越界, 要自己确保不会溢出

[[d2025-4-8]]
== 2025/4/8 实验日志
=== 今日完成工作
* 完成了复习C语言/笨办法学C/ex17-18的内容和课后题

=== 今日要点
* C语言知识点

malloc函数输入参数的单位是字节, 返回值是void*类型的指针, 表示分配的内存地址。 +
对FILE文件的fread\fwrite函数的使用必须按照顺序配套使用, 比如先后fwrite写入了int, float, struct类型数据, 就需要先后fread读取int, float, struct类型数据。 +

下面演示函数指针的用法
[source,c]
----
typedef int (*compare)(int a, int b);

int compare_sub(int a, int b) {return a - b;}
int compare_add(int a, int b) {return a + b;}

// 这里使用方式如下, 将函数指针作为参数传入其他函数中
int use(compare cmp, int a, int b) {
    return cmp(a, b);
}
int main() {
    int a = 1, b = 2;
    printf("%d\n", use(compare_sub, a, b)); // 输出 -1
    printf("%d\n", use(compare_add, a, b)); // 输出 3
}
----

[[d2025-4-9]]
== 2025/4/9 实验日志
=== 今日完成工作
* 完成了复习C语言/笨办法学C/ex32-33的平替内容(学习了单向链表, 双向链表, 并使用链表完成了冒泡排序和归并排序)

[[d2025-4-14]]
== 2025/4/14 实验日志
=== 今日完成工作
* 完成数电实验/实验一 选择器/实验二 译码器/实验三 ALU/实验六 移位寄存器
* 掌握了verilator两种仿真模板的格式

[[d2025-4-15]]
== 2025/4/15 实验日志
=== 今日完成任务
* 在ubuntu中安装了pdf划词翻译的软件, GoldenDict
* 完成了数电实验/实验七 PS2接口控制器和键盘输入

[[d2025-4-16]]
== 2025/4/16 实验日志
=== 今日完成任务
* 完成了直接映射的cache的C语言实现,写入逻辑实现了write back + write allocate和write through + non-write allocate

=== 今日要点
cache直接映射的实现不用考虑替换策略

[[d2025-4-21]]
== 2025/4/21 实验日志
=== 今日完成任务
* 完成了PA1实验的RTFSC和基础设施: 简易调试器

=== 今日要点
开始看nemu的源码, 学到了很多C语言的用法

* 点击链接查看(该笔记来自网络):link:html/宏的学习笔记_Fenglielie.html[宏的高级使用]
* 字符串处理函数strtok()和sscanf()
* 命令行参数处理函数getopt_long(),以及其时用到的结构体类型struct option{}
* 一些约定常见的组合,使用getopt_long()和strcut option()处理命令行参数 +
使用宏完成IFDEF(MACRO, 函数)之类的功能 +
* GUN C的关键字__attribute((aligned(4096)))实现数据4kB对齐
* GUN C的关键字__builtin_expect完成分支预测

[[d2025-4-22]]
== 2025/4/22 实验日志
=== 今日完成任务
* 经过我艰苦的coding,总算实现了PA1实验的RTFSC和基础设施: 表达式求值的部分内容——基本运算符

[[d2025-4-23]]
== 2025/4/23 实验日志
=== 今日完成任务
* 完成了PA1中表达式求值和监视点的表达式识别扩展代码，但是还没有写随机测试模块去测试代码

[[d2025-4-24]]
== 2025/4/24 实验日志
=== 今日完成任务

=== 今日BUG
[green]##1.txt文件中每行数据格式为"100 23+ 31- (99) "之类,每次用fscanf()以格式"%u %s\n"读取一行,结果发现%s没有读取到完整的字符串,以上为例,将只读取到"23+"**##::
因为在fscanf()使用%s匹配时将连续读取字符串,直到遇到第一个空白字符(可以是空格,换行或者制表符) +
解决方法:将%s替换成%[^\n],表示匹配直到换行符的所有字符

[green]##2.在gen-expr.c中生成测试案例时,因为经过了一次字符串转表达式的过程,实际运算的表达式只有数值和运算符,如何确保其的中间运算也是全部按照无符号数的运算规则执行？##::
解决方法:在生成表达式字符串时,给'-'后的子表达式之前插入一个字符串"(unsigned)",用一定的字符串空间换取无符号运算.同时在nemu的expr.c识别tokens时添加对应的token,优先级要在括号前,并将其像空格一样不做记录

[[d2025-4-28]]
== 2025/4/28 实验日志
=== 今日完成任务
* 正在完成预学习之前没做的必做题,整理并完善Pre_stduy.adoc

=== 今日BUG
[green]##在进行复习C语言/ex17的课后题时,我正在尝试把存储到FILE中的结构体成员中的数组替换为指针,但是一直报错说是非法访问内存,我当时确实没有意识到是fread和malloc的配合问题,下面我来详细解释##::
对于一个成员不包含指针的结构体变量,我们像将其存入文件中再读出可以如下操作
[source,C]
----
typedef struct inf {
    int weight;
    char name[100];
} Inf;
    Inf a = {100,"fuck you"};
    Inf b;
    FILE *fl = fopen("data.db","w");
    fwrite(&a, sizeof(Inf), 1, fl);
    fclose(fl);
    fl = fopen("data.db","r+");
    fread(&b, sizeof(Inf), 1, fl);
    fclose(fl);
----
但是当该结构体中包含指针时,该写法就不对了.比如上面的 `char name[100]` 变成 `char *name`, 这样fwrite存入文件的只是指针值,而不是该指针指向的内容,在下次读取时,该值将会指向无效的数据,哪怕你先fread再malloc也没有用,所以正确的写法应该是
[source,C]
----
typedef struct inf {
    int weight;
    char *name;
} Inf;
    Inf a,b;
    a.weight = 100;
    a.name = malloc(100);
    memset(a.name,0,100);
    b.name = malloc(100);
    FILE *fl = fopen("data.db","w");
    fwrite(&a, sizeof(int), 1, fl);
    fwrite(a.name, 100, 1, fl);
    fclose(fl);
    fl = fopen("data.db","r+");
    fread(&b, sizeof(int), 1, fl);
    fread(b.name, 100, 1, fl);
    fclose(fl);
    free(a.name);
    free(b.name);
----
综上所述,你往文件中存变量,`永远不要存指针,要存指针指向的内容`

[[d2025-5-1]]
== 2025/5/1 实验日志
=== 今日完成任务
- 浅浅地看了一下源码 
- 编写笔记git.adoc记录常用git命令和语法

=== 今日知识点
- 结构体中带有冒号是 `位域` 的一种用法
- C语言标签地址配合 `goto` 使用

[[d2025-5-4]]
== 2025/5/4 实验日志
=== 今日完成任务
- 开始完成nemu的RV32IM非特权指令的实现,目前借助am-kernels里面的cpu-test里的例子完善并验证指令

=== 今日BUG
[green]##在实现mulh指令时,头一次测试时没有出现问题,但在mul-longlong.c测试中出现问题,不是未识别指令,而是指令实现错误,这该如何解决呢?##::
后面发现错误的指令时mulh,因为我在计算乘法时,直接将两个unsigned int的源操作数直接转换为signed long的格式,这样在扩展时就是零扩展,而不是符号扩展.正确的做法需要现将unsigned int转换为int,然后再将int转换为signed long去计算.

[[d2025-5-5]]
== 2025/5/5 实验日志
=== 今日完成任务
- 继续完善和验证RV32IM的所有指令

=== 今日BUG
[green]##在riscv-tests-am的div测试中,出现了未定义的报错,报错如下 `==8538==ERROR: AddressSanitizer: FPE on unknown address 0x5df0d6b737bc (pc 0x5df0d6b737bc bp 0x7dcaf0b2ad20 sp 0x7ffe14f7ac30 T0)` 为什么呢?##::
发现了两种情况,一个是除以0的情况,这种情况下需要特殊处理,返回word_t的最大值即可;另一个是-2147483648/-1,在有符号除法时,前者为int的最小值,按理说得到结果应该为2147483648,但是int的最大值是2147483647,故产生了未定义变量,这种情况下需要特殊处理,直接返回-2147483648即可. +
同理若是在有符号求余时也需要考虑这两种情况,只是返回值不同.第一种返回被除数op1,第二种返回0.

[[d2025-5-7]]
== 2025/5/7 实验日志
=== 今日完成任务
* 学习make的语法,完善makefile.adoc笔记
* 开始完成PA2.2中的内容,完善abstrac-machine中的kib涉及到的库函数

=== 今日知识点
- 函数参数可以使用const修饰,表示只读,当const修饰的参数是指针时有两种情况 +
`const char *src` 表示指针指向的内容只读 +
`char *const src` 表示指针本身只读 +

[[d2025-5-8]]
== 2025/5/8 实验日志
=== 今日完成任务
* 实现了sprintf()函数
* 实现了iringbuf

[[d2025-5-9]]
== 2025/5/9 实验日志
=== 今日完成任务
* 实现了mtracer和ftracer的功能

[[d2025-5-21]]
== 2025/5/21 实验日志
=== 今日完成任务
* 使用native测试了kib的string.h中的函数以及printf函数完成了nemu和spike的DiffTest
* 完成npc第一条指令addi 

[[d2025-6-29]]
== 2025/6/29 实验日志
=== 今日要点
我错误地认为risc-v使用a0传递参数,使用a1传递返回值.实际上risc-v使用a0-a8以及栈来传递参数,
使用a0,a1以及栈来传递返回值.

=== 今日BUG
[green]##在完成PA4.1 git rt-thread时, 我发现make init## + 
[red]##ImportError: cannot import name 'mk_rtconfig' from 'menuconfig' (/usr/lib/python3/dist-packages/menuconfig.py):
File "/home/yunhai/ysyx-workbench/Templates/rt-thread-am/bsp/abstract-machine/SConstruct", line 28:objs = PrepareBuilding(env, RTT_ROOT, has_libcpu = True)
File "/home/yunhai/ysyx-workbench/Templates/rt-thread-am/bsp/abstract-machine/../../tools/building.py", line 362:
from menuconfig import mk_rtconfig
make: *** [Makefile:18: rtconfig.h] Error 2##
[green]##这是因为系统的python工具中有menuconfig这个包, 而rt-thread也提供了menuconfig.py文件,这让脚本SConstruct不知道该如何选择, 所以生成了空文件, 在第二次使用make init前如果没有将这些空文件删除, 就会被脚本认为已经完成了make init操作而不会重现报错. 这样的结果就是在make ARCH=native run时, 由于rtconfig.h是空文件导致了一堆的报错, 正常情况向rtconfig.h应该存在和.config中相似的内容.##::
我们需要修改SConstruct文件, 在 *import sys* 之后插入 *sys.path.insert(0, '/home/yunhai/ysyx-workbench/Templates/rt-thread-am/tools')* 这告诉脚本, 优先在项目提供的文件中寻找对应的包.

[[d2025-8-9]]
== 2025/8/9 实验日志
=== 今日完成任务
完成至B2/更实用的Soc/内存访问测试

=== 今日要点
这次测试的是sram的堆读写功能, sram的大小为8k, 0x0f000000~0x0f002000, 0x0f002000附近1KB的大小为栈, 剩下的空间为堆

* 第一个问题: 因为main函数把所有的堆都重新写了一遍, 所以不能从main函数返回, main函数最后必须halt(0);或者while(1);
* 第二个问题: 检查读写功能是否正确使用check(A==B)会造成栈溢出, 因为这个check函数规定为了不可内联属性, 所以使用if(A!=B) halt(1);才能好用.

[[d2025-8-13]]
== 2025/8/13 实验日志
=== 今日BUG

* 问题一: 在B2的写入全局变量实验中, 修改了链接脚本, 同时用到了sram和mrom, 两部分存储的地址相差很远,由于链接脚本不正确的写法导致了elf转换得到的bin文件存在大量的**内存空洞**, 即全0, 这样bin文件就太大了. 问题脚本如下, 主要出现在.data段

[source, asm]
----
ENTRY(_start)

MEMORY {
  sram : ORIGIN = 0x0f000000, LENGTH = 8K
  mrom : ORIGIN = 0x20000000, LENGTH = 4K
}

SECTIONS {
    /* ... */
    rodata_end = .;
    . = ORIGIN(sram);
    .data : AT(rodata_end)
    {
        data_start = .;
        *(.data)
    } > sram
    data_size = SIZEOF(.data);
    data_load_start = LOADADDR(.data);
    /* ... */
}
----
该脚本得到bin文件大小为 285MB
[source, asm]
----
SECTIONS {
    /* ... */
    rodata_end = .;
    .data :
    {
        data_start = .;
        *(.data)
    } > sram AT > rodata_end
    data_size = SIZEOF(.data);
    data_load_start = LOADADDR(.data);
    /* ... */
}
----
该脚本得到bin文件大小为 532MB
[source, asm]
----
SECTIONS {
    /* ... */
    .data :
    {
        data_start = .;
        *(.data)
    } > sram AT > mrom
    data_size = SIZEOF(.data);
    data_load_start = LOADADDR(.data);
    /* ... */
}
----
该脚本得到bin文件大小为 644B +
所以问题应该是出现在了我使用rodata_end上

* 问题二: 我发现fib.c定义全局变量ans但是使用选项--print-map时, data_size确实等于0, 导致我没有正确启动bootloader? +
原因在于启动了选项-fdata-sections, 这个选项将**.data**的每个变量变成了**.data.变量名**这样的子段, 所以我的脚本中的**.data**并没有收集到这两个全局变量, 这两个全局变量子段会被自动链接到**.data**的后面, 所以data_size错误, 修改脚本如下即可

[source, asm]
----
SECTIONS {
    /* ... */
    .data :
    {
        data_start = .;
        *(.data .data.*)
    } > sram AT > mrom
    data_size = SIZEOF(.data);
    data_load_start = LOADADDR(.data);
    /* ... */
}
----

* 问题三: 程序执行错误, 检查发现对 int ans[0] = 1的四次lb操作, 并未按预想得到1,0,0,0; 而是得到了1,0,1,0这样的错误结果? +
原因是ysyxsoc的sram使用了地址4字节对齐访问, 而我使用DPI-C实现mrom并没有考虑地址4字节对齐访问, 所以我只需要给mrom添加地址4字节对齐访问即可 +
错误程序

[source, C++]
----
extern "C" void mrom_read(int32_t addr, int32_t *data) {
  *data = *(int32_t *)guest_to_host((uint32_t)addr);
}
----
正确程序
[source, C++]
----
extern "C" void mrom_read(int32_t addr, int32_t *data) {
  int32_t raddr = addr & (~0x3);
  *data = *(int32_t *)guest_to_host((uint32_t)raddr);
}
----

[[d2025-8-18]]
== 2025/8/18 实验日志
=== 今日完成任务
完成至B2/从flash中取指

=== 今日BUG
* 这里我CPU从mrom执行跳转到了sram执行, 但是执行时候报了读权限错误. 这是因为我的npc的cpu.cpp中用来记录执行指令时, 使用了 `inst_pre = *(uint32_t *)(pmem + pc_pre - CONFIG_MBASE);` ,这就意味着我的PC值不应该超出pmem的范围